## The below is simply for the sake editing kind's cluster config in the IDE
apiVersion: v1
kind: List
items:
- apiVersion: apiextensions.k8s.io/v1
  kind: CustomResourceDefinition
  metadata:
    name: clusters.kind.x-k8s.io
  spec:
    conversion:
      strategy: None
    group: kind.x-k8s.io
    names:
      kind: Cluster
      plural: clusters
    scope: Namespaced
    versions:
    - name: v1alpha4
      served: true
      storage: true
      schema:
        openAPIV3Schema:

          type: object
          properties:
            apiVersion:
              type: string
            containerdConfigPatches:
              type: array
              items:
                type: string
            containerdConfigPatchesJSON6902:
              type: array
              items:
                type: string
            featureGates:
              type: object
              additionalProperties:
                type: boolean
            kind:
              type: string
            kubeadmConfigPatches:
              type: array
              items:
                type: string
#            kubeadmConfigPatchesJSON6902:
#              type: array
#              items:
#                "$ref": "#/components/schemas/PatchJSON6902"
            name:
              type: string
            networking:
              type: object
              properties:
                apiServerAddress:
                  type: string
                apiServerPort:
                  type: integer
                  format: int32
                disableDefaultCNI:
                  type: boolean
                ipFamily:
                  type: string
                kubeProxyMode:
                  type: string
                podSubnet:
                  type: string
                serviceSubnet:
                  type: string
              additionalProperties: false
            nodes:
              type: array
              items:
                type: object
                properties:
                  extraMounts:
                    type: array
                    items:
                      type: object
                      properties:
                        containerPath:
                          type: string
                        hostPath:
                          type: string
                        propagation:
                          type: string
                        readOnly:
                          type: boolean
                        selinuxRelabel:
                          type: boolean
                      additionalProperties: false
                  extraPortMappings:
                    type: array
                    items:
                      type: object
                      properties:
                        containerPort:
                          type: integer
                          format: int32
                        hostPort:
                          type: integer
                          format: int32
                        listenAddress:
                          type: string
                        protocol:
                          type: string
                      additionalProperties: false
                  image:
                    type: string
                  kubeadmConfigPatches:
                    type: array
                    items:
                      type: string
                  kubeadmConfigPatchesJSON6902:
                    type: array
                    items:
                      type: object
                      properties:
                        group:
                          type: string
                        kind:
                          type: string
                        patch:
                          type: string
                        version:
                          type: string
                      additionalProperties: false
                      required:
                      - group
                      - version
                      - kind
                      - patch
                  labels:
                    type: object
                    additionalProperties:
                      type: string
                  role:
                    type: string
                additionalProperties: false
            runtimeConfig:
              type: object
              additionalProperties:
                type: string
          additionalProperties: false

