---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-registry-kind
spec:
  storageClassName: {{ hasKey .Values "storageClassName" | ternary .Values.storageClassName "standard" }}
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 30Gi
  hostPath:
    path: /local-cluster/data/docker-registry
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-registry-kind
spec:
  volumeName: docker-registry-kind
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi