apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: doppler-store
spec:
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            name: {{ .Values.configuration.doppler.secret.name }}
            namespace: {{ .Release.Namespace }}
            key: {{ .Values.configuration.doppler.secret.key }}
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: doppler-store-push
spec:
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            name: {{ .Values.configuration.doppler.pushSecret.name }}
            namespace: {{ .Release.Namespace }}
            key: {{ .Values.configuration.doppler.pushSecret.key }}
