---
# We'll bootstrap the token here after the first time
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.configuration.doppler.secret.name }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-store

  target:
    name: {{ .Values.configuration.doppler.secret.name }}

  data:
    - secretKey: {{.Values.configuration.doppler.secret.key }}
      remoteRef:
        key: ES_DOPPLER_SECRET_TOKEN

---
{{- if .Values.configuration.doppler.push.enabled }}

# Use this token to push tokens from within cluster to doppler
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.configuration.doppler.push.secret.name }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-store

  target:
    name: {{ .Values.configuration.doppler.push.secret.name }}

  data:
    - secretKey: {{.Values.configuration.doppler.push.secret.key }}
      remoteRef:
        key: ES_DOPPLER_PUSH_SECRET_TOKEN
{{- end }}