docker-registry:
  service:
    port: 80
  persistence:
    enabled: true
    existingClaim: docker-registry-kind
  securityContext:
    fsGroup: 1000
    runAsUser: 1000
  garbageCollect:
    enabled: true

deletion:
  enabled: true
  schedule: "0 2 * * *"

domain:
  suffix: ""