docker-registry:
  service:
    port: 80
  persistence:
    enabled: true
    existingClaim: docker-registry-kind
    deleteEnabled: true
  securityContext:
    fsGroup: 1000
    runAsUser: 1000
  garbageCollect:
    enabled: true
  priorityClassName: system-node-critical
  # https://github.com/twuni/docker-registry.helm/issues/104
  configData:
    storage:
      cache:
        blobdescriptor: disabled

deletion:
  enabled: true
  schedule: "0 2 * * *"

domain:
  suffix: ""
