apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-apps
spec:
  generators:
    - git:
        repoURL: "{{ .Values.repository.url }}"
        revision: HEAD
        files:
          - path: "apps/**/config.json"
  goTemplate: true
  template:
    metadata:
      name: '{{`{{ .name }}`}}'
      annotations:
        "home.stackpwn.in/icon-url": '{{`{{ .iconUrl | quote }}`}}'
        "kubernetes.io/description": '{{`{{ .description | quote }}`}}'
    spec:
      info:
        - name: description
          value: '{{`{{ .description | quote }}`}}'
        - name: iconUrl
          value: '{{`{{ .iconUrl | quote }}`}}'
      source:
        repoURL: "{{ .Values.repository.url }}"
        targetRevision: HEAD
        path: '{{`{{ .path.path }}`}}'
        helm:
          parameters:
            - name: "domain.suffix"
              value: ".home.stackpwn.in"
            - name: "storageClassName" # standard for kind, local-path for k3d
              value: "local-path"
            - name: "cluster.type"
              value: "k3d"
            - name: "tailscale.ip"
              value: "100.125.182.56"

      destination:
        name: 'in-cluster'
        namespace: '{{`{{ .namespace }}`}}'
      project: '{{`{{ .project }}`}}'
      ignoreDifferences:
        {{- range $index, $crdName := list "addresspools.metallb.io" "bgppeers.metallb.io" }}
        - kind: CustomResourceDefinition
          group: apiextensions.k8s.io
          name: {{ $crdName }}
          jsonPointers:
            - /spec/conversion/webhook/clientConfig/caBundle
        {{- end }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
