apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-store

  target:
    name: argocd-secret
{{/*    creationPolicy: Merge*/}}
    template:
      engineVersion: v2
      data:
        "admin.password": '{{`{{  htpasswd "admin" (.ARGO_UI_ADMIN_PASSWORD) | trimPrefix "admin:" }}`}}'
        "admin.passwordMtime": '{{`{{ now | date "2023-03-31T15:45:52IST" }}`}}'
        {{- if .Values.github.webhookSecret.enabled }}
        "webhook.github.secret": '{{`{{ .GITHUB_ACTIONS_ARGO_WEBHOOK_SECRET }}`}}'
        {{- end}}
        "server.secretKey": ""

  data:
    - secretKey: ARGO_UI_ADMIN_PASSWORD
      remoteRef:
        key: ARGO_UI_ADMIN_PASSWORD
      {{- if .Values.github.webhookSecret.enabled }}
    - secretKey: GITHUB_ACTIONS_ARGO_WEBHOOK_SECRET
      remoteRef:
        key: GITHUB_ACTIONS_ARGO_WEBHOOK_SECRET
      {{- end}}
