apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-notifications-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-store

  target:
    name: argocd-notifications-secret
    template:
      engineVersion: v2
      data:
        {{- if .Values.notifications.discord.enabled }}
        "discord-webhook-url": '{{`{{  .ARGO_DISCORD_SYNC_WEBHOOK }}`}}'
        {{- end}}
  data:
    {{- if .Values.notifications.discord.enabled }}
    - secretKey: ARGO_DISCORD_SYNC_WEBHOOK
      remoteRef:
        key: ARGO_DISCORD_SYNC_WEBHOOK
    {{- end}}