{{- if .Values.ghCliWebhookForwarder.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gh-webhook
  labels:
    {{- include "argocd.gh-webhook.labels" . | nindent 4 }}

spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-store

  target:
    name: gh-webhook
    template:
      engineVersion: v2
      data:
        GH_TOKEN: '{{`{{  .ARGO_GH_WEBHOOK_TOKEN }}`}}'

  data:
    - secretKey: ARGO_GH_WEBHOOK_TOKEN
      remoteRef:
        key: ARGO_GH_WEBHOOK_TOKEN
{{- end }}