apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: home-k8s-gitops-creds
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-store

  target:
    name: home-k8s-gitops-creds
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      engineVersion: v2
      data:
        type: git
        url: "{{ .Values.repository.url }}"
        username: '{{`{{ .ARGO_GITHUB_USERNAME }}`}}'
        password: '{{`{{ .ARGO_GITHUB_PASSWORD }}`}}'

  data:
    - secretKey: ARGO_GITHUB_USERNAME
      remoteRef:
        key: ARGO_GITHUB_USERNAME
    - secretKey: ARGO_GITHUB_PASSWORD
      remoteRef:
        key: ARGO_GITHUB_PASSWORD
