argo-cd:
  configs:
    params:
      server.insecure: true
  server:
    autoscaling:
      maxReplicas: 2
    clusterAdminAccess:
      enabled: true
    config:
      resource.compareoptions: |
        # if ignoreAggregatedRoles set to true then differences caused by aggregated roles in RBAC resources are ignored.
        ignoreAggregatedRoles: true
        # disables status field diffing in specified resource types
        # 'crd' - CustomResourceDefinitions (default)
        # 'all' - all resources
        # 'none' - disabled
        ignoreResourceStatusField: all

  controller:
    clusterAdminAccess:
      enabled: true
  repoServer:
    autoscaling:
      maxReplicas: 2
    clusterAdminAccess:
      enabled: true

repository:
  url: https://github.com/iamKunal/home-k8s-gitops.git

domain:
  suffix: ""

ghWebhook:
  image:
    repository: "registry.docker.home.stackpwn.in:80/gh-cli"
    tag: latest
    pullPolicy: Always
  events: "push"
  replicaCount: 0
