argo-cd:
  configs:
    params:
      server.insecure: true
  server:
    autoscaling:
      maxReplicas: 2
    clusterAdminAccess:
      enabled: true
  controller:
    clusterAdminAccess:
      enabled: true
  repoServer:
    autoscaling:
      maxReplicas: 2
    clusterAdminAccess:
      enabled: true
    volumeMounts:
      - name: helm-values
        mountPath: /helmValues
    volumes:
      - name: helm-values
        secret:
          secretName: argo-helm-secret-values
          optional: true

repository:
  url: https://github.com/iamKunal/home-k8s-gitops.git

domain:
  suffix: ""