argo-cd:
  configs:
    params:
      server.insecure: true
    secret:
      createSecret: false
  server:
    autoscaling:
      maxReplicas: 2
    clusterAdminAccess:
      enabled: true
  controller:
    clusterAdminAccess:
      enabled: true
  repoServer:
    autoscaling:
      maxReplicas: 2
    clusterAdminAccess:
      enabled: true
  notifications:
    cm:
      create: false
repository:
  url: https://github.com/iamKunal/home-k8s-gitops.git

domain:
  suffix: ""

github:
  webhookSecret:
    enabled: true

ghCliWebhookForwarder:
  enabled: true
  image:
    repository: "registry.docker.home.stackpwn.in:80/gh-cli"
    tag: latest
    pullPolicy: Always
  events: "push"
  replicaCount: 1

notifications:
  discord:
    enabled: true
