argo-cd:
  configs:
    params:
      server.insecure: true
  server:
    autoscaling:
      maxReplicas: 2
    clusterAdminAccess:
      enabled: true
  controller:
    clusterAdminAccess:
      enabled: true
  repoServer:
    autoscaling:
      maxReplicas: 2
    clusterAdminAccess:
      enabled: true

repository:
  url: https://github.com/iamKunal/home-k8s-gitops.git

domain:
  suffix: ""

ghWebhook:
  image:
    repository: "registry.docker.home.stackpwn.in:80/gh-cli"
    tag: latest
    pullPolicy: IfNotPresent
  events: "push"
